# Config package
from .analysis_config import (
    SIMILARITY_THRESHOLD,
    MAX_ARTICLES_PER_RUN,
    MAX_LLM_CALLS,
    SIGNAL_COOLDOWN_HOURS,
    ARTICLE_TIME_WINDOW_HOURS,
    STOP_WORDS,
    TOPIC_KEYWORDS,
    SIGNAL_THRESHOLDS,
    LLM_PROMPTS,
    SIGNAL_TYPES,
    DATA_SOURCES,
    FRED_SERIES,
)

__all__ = [
    "SIMILARITY_THRESHOLD",
    "MAX_ARTICLES_PER_RUN",
    "MAX_LLM_CALLS",
    "SIGNAL_COOLDOWN_HOURS",
    "ARTICLE_TIME_WINDOW_HOURS",
    "STOP_WORDS",
    "TOPIC_KEYWORDS",
    "SIGNAL_THRESHOLDS",
    "LLM_PROMPTS",
    "SIGNAL_TYPES",
    "DATA_SOURCES",
    "FRED_SERIES",
]
