# 实体类型识别配置
# 用于自动识别实体类型 (person/organization/location/event/concept)
# 可根据需要添加自定义关键词

ENTITY_TYPES = {
    "event": {
        "description": "事件",
        "keywords": {
            "zh": [
                "事件",
                "事故",
                "危机",
                "战争",
                "冲突",
                "革命",
                "起义",
                "会议",
                "峰会",
                "论坛",
                "谈判",
                "协议",
                "条约",
                "大选",
                "选举",
                "投票",
                "公投",
                "疫情",
                "灾害",
                "灾难",
                "地震",
                "洪水",
                "火灾",
                "奥运会",
                "世界杯",
                "锦标赛",
                "比赛",
                "游行",
                "抗议",
                "罢工",
                "示威",
            ],
            "en": [
                " recession",
                " depression",
                " crisis",
                " war",
                " conflict",
                " revolution",
                " uprising",
                " rebellion",
                " coup",
                " summit",
                " conference",
                " meeting",
                " forum",
                " treaty",
                " agreement",
                " election",
                " referendum",
                " vote",
                " polling",
                " ballot",
                " pandemic",
                " epidemic",
                " outbreak",
                " plague",
                " disaster",
                " catastrophe",
                " tragedy",
                " earthquake",
                " flood",
                " fire",
                " Olympics",
                " World Cup",
                " championship",
                " tournament",
                " game",
                " protest",
                " demonstration",
                " march",
                " rally",
                " strike",
                " scandal",
                " controversy",
                " incident",
                " accident",
            ],
        },
    },
    "organization": {
        "description": "组织/公司",
        "keywords": {
            "zh": [
                "公司",
                "集团",
                "银行",
                "大学",
                "学院",
                "学校",
                "研究所",
                "协会",
                "学会",
                "委员会",
                "理事会",
                "联合会",
                "联盟",
                "部",
                "局",
                "厅",
                "司",
                "处",
                "科",
                "社",
                "所",
                "院",
                "台",
                "厂",
                "站",
                "中心",
                "军队",
                "部队",
                "军团",
                "舰队",
                "空军",
                "海军",
                "党",
                "派",
                "团",
                "工会",
                "媒体",
                "报社",
                "杂志社",
                "出版社",
                "通讯社",
                "法院",
                "检察院",
                "警察局",
                "大使馆",
                "领事馆",
            ],
            "en": [
                " CNN",
                " BBC",
                " CBS",
                " NBC",
                " ABC",
                " Fox",
                " ESPN",
                " HBO",
                " Netflix",
                " Inc",
                " Corp",
                " Corporation",
                " Ltd",
                " LLC",
                " PLC",
                " Co",
                " Company",
                " Companies",
                " Group",
                " Holdings",
                " Partners",
                " Associates",
                " Bank",
                " Banking",
                " Financial",
                " Capital",
                " Investment",
                " Securities",
                " Fund",
                " Trust",
                " Insurance",
                " Exchange",
                " University",
                " College",
                " Institute",
                " Academy",
                " School",
                " Association",
                " Society",
                " Union",
                " Committee",
                " Council",
                " Commission",
                " Department",
                " Agency",
                " Bureau",
                " Administration",
                " Office",
                " Organization",
                " Foundation",
                " Institution",
                " Corporation",
                " Party",
                " Movement",
                " Coalition",
                " Alliance",
                " Army",
                " Navy",
                " Air Force",
                " Marines",
                " Guard",
                " Corps",
                " Police",
                " Sheriff",
                " FBI",
                " CIA",
                " NSA",
                " Pentagon",
                " Times",
                " Post",
                " Journal",
                " Tribune",
                " Gazette",
                " Herald",
                " News",
                " Media",
                " Press",
                " Network",
                " Broadcasting",
                " Radio",
                " TV",
                " Studio",
                " Records",
                " Productions",
                " Entertainment",
                " Tech",
                " Technologies",
                " Solutions",
                " Services",
                " Systems",
                " Industries",
                " Enterprises",
                " Ventures",
                " Capital",
            ],
        },
    },
    "location": {
        "description": "地点",
        "keywords": {
            "zh": [
                "国",
                "国家",
                "地区",
                "洲",
                "洋",
                "海",
                "湾",
                "海峡",
                "运河",
                "州",
                "省",
                "市",
                "县",
                "区",
                "镇",
                "乡",
                "村",
                "街",
                "路",
                "大道",
                "大街",
                "胡同",
                "巷",
                "广场",
                "公园",
                "花园",
                "校园",
                "园区",
                "山",
                "山脉",
                "峰",
                "岭",
                "丘",
                "陵",
                "河",
                "江",
                "湖",
                "泊",
                "潭",
                "溪",
                "涧",
                "沟",
                "渠",
                "海",
                "洋",
                "湾",
                "港",
                "口",
                "岸",
                "关",
                "岛",
                "礁",
                "屿",
                "沙漠",
                "草原",
                "森林",
                "湿地",
                "沼泽",
                "盆地",
                "高原",
                "平原",
            ],
            "en": [
                # 国家
                " America",
                " United States",
                " USA",
                " US",
                " China",
                " Chinese",
                " Russia",
                " Russian",
                " Japan",
                " Japanese",
                " Korea",
                " Korean",
                " India",
                " Indian",
                " Germany",
                " German",
                " France",
                " French",
                " Britain",
                " British",
                " UK",
                " England",
                " English",
                " Canada",
                " Canadian",
                " Mexico",
                " Mexican",
                " Brazil",
                " Brazilian",
                " Australia",
                " Australian",
                " Italy",
                " Italian",
                " Spain",
                " Spanish",
                " Portugal",
                " Portuguese",
                " Netherlands",
                " Dutch",
                " Belgium",
                " Belgian",
                " Switzerland",
                " Swiss",
                " Austria",
                " Austrian",
                " Sweden",
                " Swedish",
                " Norway",
                " Norwegian",
                " Denmark",
                " Danish",
                " Finland",
                " Finnish",
                " Poland",
                " Polish",
                " Czech",
                " Hungary",
                " Hungarian",
                " Greece",
                " Greek",
                " Turkey",
                " Turkish",
                " Iran",
                " Iranian",
                " Iraq",
                " Iraqi",
                " Syria",
                " Syrian",
                " Israel",
                " Israeli",
                " Palestine",
                " Palestinian",
                " Jordan",
                " Jordanian",
                " Lebanon",
                " Lebanese",
                " Saudi Arabia",
                " Saudi",
                " UAE",
                " Emirates",
                " Qatar",
                " Kuwait",
                " Egypt",
                " Egyptian",
                " Libya",
                " Libyan",
                " Tunisia",
                " Algeria",
                " Morocco",
                " Sudan",
                " Ethiopia",
                " Kenya",
                " Nigeria",
                " South Africa",
                " Ukraine",
                " Ukrainian",
                " Belarus",
                " Moldova",
                " Romania",
                " Bulgaria",
                " Serbia",
                " Croatia",
                " Vietnam",
                " Vietnamese",
                " Thailand",
                " Thai",
                " Malaysia",
                " Malaysian",
                " Indonesia",
                " Indonesian",
                " Philippines",
                " Filipino",
                " Singapore",
                " Singaporean",
                " Taiwan",
                " Hong Kong",
                " Macau",
                " Mongolia",
                " Mongolian",
                " Kazakhstan",
                " Uzbekistan",
                " Pakistan",
                " Pakistani",
                " Bangladesh",
                " Bangladeshi",
                " Myanmar",
                " Burma",
                " Cambodia",
                " Laos",
                " Afghanistan",
                " Nepal",
                " Bhutan",
                " Sri Lanka",
                " Argentina",
                " Chile",
                " Peru",
                " Colombia",
                " Venezuela",
                " Cuba",
                " Venezuela",
                " Ecuador",
                " New Zealand",
                " Zealand",
                " Fiji",
                " Papua",
                # 美国州
                " Alabama",
                " Alaska",
                " Arizona",
                " Arkansas",
                " California",
                " Colorado",
                " Connecticut",
                " Delaware",
                " Florida",
                " Georgia",
                " Hawaii",
                " Idaho",
                " Illinois",
                " Indiana",
                " Iowa",
                " Kansas",
                " Kentucky",
                " Louisiana",
                " Maine",
                " Maryland",
                " Massachusetts",
                " Michigan",
                " Minnesota",
                " Mississippi",
                " Missouri",
                " Montana",
                " Nebraska",
                " Nevada",
                " Hampshire",
                " Jersey",
                " Mexico",
                " York",
                " Carolina",
                " Dakota",
                " Ohio",
                " Oklahoma",
                " Oregon",
                " Pennsylvania",
                " Rhode",
                " Tennessee",
                " Texas",
                " Utah",
                " Vermont",
                " Virginia",
                " Washington",
                " Wisconsin",
                " Wyoming",
                " DC",
                " Columbia",
                # 地理特征
                " County",
                " Parish",
                " Borough",
                " City",
                " Town",
                " Village",
                " Township",
                " Municipality",
                " District",
                " Region",
                " Area",
                " Zone",
                " Territory",
                " Peninsula",
                " Cape",
                " Isthmus",
                " Coast",
                " Shore",
                " Beach",
                " Port",
                " Harbor",
                " Valley",
                " Canyon",
                " Gorge",
                " Ravine",
                " Mountain",
                " Mount",
                " Peak",
                " Summit",
                " Ridge",
                " Range",
                " Hill",
                " Plateau",
                " Mesa",
                " Butte",
                " Island",
                " Isle",
                " Archipelago",
                " Atoll",
                " Reef",
                " Lake",
                " Pond",
                " Reservoir",
                " Dam",
                " River",
                " Creek",
                " Stream",
                " Brook",
                " Canal",
                " Sea",
                " Ocean",
                " Bay",
                " Gulf",
                " Sound",
                " Strait",
                " Channel",
                " Passage",
                " Desert",
                " Dune",
                " Oasis",
                " Forest",
                " Woods",
                " Jungle",
                " Rainforest",
                " Prairie",
                " Steppe",
                " Tundra",
                " Savanna",
                " Swamp",
                " Marsh",
                " Bog",
                " Wetland",
                " Park",
                " Garden",
                " Plaza",
                " Square",
                " Airport",
                " Station",
                " Terminal",
                " Bridge",
                " Tunnel",
                " Road",
                " Highway",
                " Freeway",
                " Street",
                " Avenue",
                " Boulevard",
                " Drive",
                " Lane",
                " Way",
                " Center",
                " Centre",
                " Building",
                " Tower",
                " Complex",
                " Border",
                " Boundary",
                " Frontier",
                " Perimeter",
                " North",
                " South",
                " East",
                " West",
                " Northeast",
                " Northwest",
                " Southeast",
                " Southwest",
                " Atlantic",
                " Pacific",
                " Indian",
                " Arctic",
                " Antarctic",
                " Mediterranean",
                " Caribbean",
                " Baltic",
                " Black Sea",
                " Red Sea",
                " Amazon",
                " Nile",
                " Mississippi",
                " Yangtze",
                " Yellow River",
                " Alps",
                " Rockies",
                " Andes",
                " Himalayas",
                " Caucasus",
                " Sahara",
                " Gobi",
                " Kalahari",
                " Mojave",
                " Amazonia",
                " Congo",
                " Borneo",
                " Madagascar",
            ],
        },
    },
}

# 人名识别规则
PERSON_RULES = {
    "description": "人名",
    "chinese_name_length": {"min": 2, "max": 6},
    "english_indicators": [
        "contains_space",  # 包含空格（名+姓）
        "title_capitalized",  # 首字母大写
    ],
    # 常见英文名/姓氏（用于辅助判断）
    "common_english_names": [
        "James",
        "John",
        "Robert",
        "Michael",
        "William",
        "David",
        "Richard",
        "Joseph",
        "Thomas",
        "Charles",
        "Daniel",
        "Matthew",
        "Anthony",
        "Mark",
        "Donald",
        "Steven",
        "Paul",
        "Andrew",
        "Kenneth",
        "Joshua",
        "Kevin",
        "Brian",
        "George",
        "Timothy",
        "Ronald",
        "Edward",
        "Jason",
        "Jeffrey",
        "Ryan",
        "Jacob",
        "Gary",
        "Nicholas",
        "Eric",
        "Jonathan",
        "Stephen",
        "Larry",
        "Justin",
        "Scott",
        "Brandon",
        "Benjamin",
        "Samuel",
        "Gregory",
        "Frank",
        "Alexander",
        "Raymond",
        "Patrick",
        "Jack",
        "Dennis",
        "Jerry",
        "Tyler",
        "Aaron",
        "Jose",
        "Adam",
        "Nathan",
        "Henry",
        "Douglas",
        "Zachary",
        "Peter",
        "Kyle",
        "Ethan",
        "Walter",
        "Noah",
        "Jeremy",
        "Christian",
        "Keith",
        "Roger",
        "Terry",
        "Gerald",
        "Harold",
        "Sean",
        "Austin",
        "Carl",
        "Arthur",
        "Lawrence",
        "Dylan",
        "Jesse",
        "Jordan",
        "Bryan",
        "Billy",
        "Joe",
        "Bruce",
        "Gabriel",
        "Logan",
        "Albert",
        "Willie",
        "Alan",
        "Juan",
        "Wayne",
        "Elijah",
        "Randy",
        "Roy",
        "Vincent",
        "Ralph",
        "Eugene",
        "Russell",
        "Bobby",
        "Mason",
        "Philip",
        "Louis",
        "Mary",
        "Patricia",
        "Jennifer",
        "Linda",
        "Elizabeth",
        "Barbara",
        "Susan",
        "Jessica",
        "Sarah",
        "Karen",
        "Nancy",
        "Lisa",
        "Betty",
        "Margaret",
        "Sandra",
        "Ashley",
        "Kimberly",
        "Emily",
        "Donna",
        "Michelle",
        "Dorothy",
        "Carol",
        "Amanda",
        "Melissa",
        "Deborah",
        "Stephanie",
        "Rebecca",
        "Laura",
        "Sharon",
        "Cynthia",
        "Kathleen",
        "Amy",
        "Shirley",
        "Angela",
        "Helen",
        "Anna",
        "Brenda",
        "Pamela",
        "Nicole",
        "Emma",
        "Samantha",
        "Katherine",
        "Christine",
        "Debra",
        "Rachel",
        "Catherine",
        "Carolyn",
        "Janet",
        "Ruth",
        "Maria",
        "Heather",
        "Diane",
        "Virginia",
        "Julie",
        "Joyce",
        "Victoria",
        "Olivia",
        "Kelly",
        "Christina",
        "Lauren",
        "Joan",
        "Evelyn",
        "Judith",
        "Megan",
        "Cheryl",
        "Andrea",
        "Hannah",
        "Martha",
        "Jacqueline",
        "Frances",
        "Gloria",
        "Ann",
        "Teresa",
        "Kathryn",
        "Sara",
        "Janice",
        "Jean",
        "Alice",
        "Madison",
        "Doris",
        "Abigail",
        "Julia",
        "Judy",
        "Grace",
        "Denise",
        "Amber",
        "Marilyn",
        "Beverly",
        "Danielle",
        "Theresa",
        "Sophia",
        "Marie",
        "Diana",
        "Brittany",
        "Natalie",
        "Isabella",
        "Charlotte",
        "Rose",
        "Alexis",
        "Kayla",
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Garcia",
        "Miller",
        "Davis",
        "Rodriguez",
        "Martinez",
        "Hernandez",
        "Lopez",
        "Gonzalez",
        "Wilson",
        "Anderson",
        "Thomas",
        "Taylor",
        "Moore",
        "Jackson",
        "Martin",
        "Lee",
        "Perez",
        "Thompson",
        "White",
        "Harris",
        "Sanchez",
        "Clark",
        "Ramirez",
        "Lewis",
        "Robinson",
        "Walker",
        "Young",
        "Allen",
        "King",
        "Wright",
        "Scott",
        "Torres",
        "Nguyen",
        "Hill",
        "Flores",
        "Green",
        "Adams",
        "Nelson",
        "Baker",
        "Hall",
        "Rivera",
        "Campbell",
        "Mitchell",
        "Carter",
        "Roberts",
        "Gomez",
        "Phillips",
        "Evans",
        "Turner",
        "Diaz",
        "Parker",
        "Cruz",
        "Edwards",
        "Collins",
        "Reyes",
        "Stewart",
        "Morris",
        "Morales",
        "Murphy",
        "Cook",
        "Rogers",
        "Gutierrez",
        "Ortiz",
        "Morgan",
        "Cooper",
        "Peterson",
        "Bailey",
        "Reed",
        "Kelly",
        "Howard",
        "Ramos",
        "Kim",
        "Cox",
        "Ward",
        "Richardson",
        "Watson",
        "Brooks",
        "Chavez",
        "Wood",
        "James",
        "Bennett",
        "Gray",
        "Mendoza",
        "Ruiz",
        "Hughes",
        "Price",
        "Alvarez",
        "Castillo",
        "Sanders",
        "Patel",
        "Myers",
        "Long",
        "Ross",
        "Foster",
        "Jimenez",
        "Powell",
        "Jenkins",
        "Perry",
        "Russell",
        "Sullivan",
        "Bell",
        "Coleman",
        "Butler",
        "Henderson",
        "Barnes",
        "Gonzales",
        "Fisher",
        "Vasquez",
        "Simmons",
        "Romero",
        "Jordan",
        "Patterson",
        "Alexander",
        "Hamilton",
        "Graham",
        "Reynolds",
        "Griffin",
        "Wallace",
        "Moreno",
        "West",
        "Cole",
        "Hayes",
        "Bryant",
        "Herrera",
        "Gibson",
        "Ellis",
        "Tran",
        "Medina",
        "Aguilar",
        "Stevens",
        "Murray",
        "Ford",
        "Castro",
        "Marshall",
        "Owens",
        "Harrison",
        "Fernandez",
        "Woods",
        "Washington",
        "Kennedy",
        "Wells",
        "Vargas",
        "Henry",
        "Chen",
        "Freeman",
        "Webb",
        "Tucker",
        "Guzman",
        "Burns",
        "Crawford",
        "Olson",
        "Simpson",
        "Porter",
        "Hunter",
        "Gordon",
        "Mendez",
        "Silva",
        "Shaw",
        "Snyder",
        "Mason",
        "Dixon",
        "Munoz",
        "Hunt",
        "Hicks",
        "Holmes",
        "Palmer",
        "Wagner",
        "Black",
        "Robertson",
        "Boyd",
        "Rose",
        "Stone",
        "Salazar",
        "Fox",
        "Warren",
        "Mills",
        "Meyer",
        "Rice",
        "Schmidt",
        "Garza",
        "Daniels",
        "Ferguson",
        "Nichols",
        "Stephens",
        "Soto",
        "Weaver",
        "Ryan",
        "Gardner",
        "Payne",
        "Grant",
        "Dunn",
        "Kelley",
        "Spencer",
        "Hawkins",
        "Arnold",
        "Pierce",
        "Vazquez",
        "Hansen",
        "Peters",
        "Santos",
        "Hart",
        "Bradley",
        "Knight",
        "Elliott",
        "Cunningham",
        "Duncan",
        "Armstrong",
        "Hudson",
        "Carroll",
        "Lane",
        "Riley",
        "Andrews",
        "Alvarado",
        "Ray",
        "Delgado",
        "Berry",
        "Perkins",
        "Hoffman",
        "Johnston",
        "Matthews",
        "Pena",
        "Richards",
        "Contreras",
        "Willis",
        "Carpenter",
        "Lawrence",
    ],
}

# 概念（默认类型）
CONCEPT_RULES = {
    "description": "概念/主题",
    "note": "当不满足其他类型规则时，默认为概念类型",
}

# 检测优先级（从高到低）
# 如果一个实体匹配多个类型，按此优先级选择
DETECTION_PRIORITY = ["event", "organization", "location", "person", "concept"]

# 最小实体名称长度
MIN_ENTITY_LENGTH = 2

# 最大实体名称长度（用于缓存键生成）
MAX_ENTITY_LENGTH = 100
