name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'workers/content-extractor/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: workers/content-extractor
        run: npm install
      
      - name: Deploy Worker
        working-directory: workers/content-extractor
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler deploy
